language: objective-c

branches:
 only:
 - master

xcode_project: onthemap.xcodeproj
xcode_scheme: onthemap
osx_image: xcode7.1
xcode_sdk: iphonesimulator9.1 

script: xcodebuild clean build test -project onthemap.xcodeproj -scheme onthemapTests build  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO