language: objective-c

branches:
 only:
 - master

osx_image: xcode7.1
xcode_sdk: iphonesimulator9.1 

script: 
    - set -o pipefail
        &&
        xcodebuild -verbose
        -project onthemap.xcodeproj
        -scheme onthemapTests
        -sdk macosx
        clean build test
        -enableCodeCoverage YES
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        | xcpretty -c

after_success: - bash <(curl -s https://codecov.io/bash)