language: objective-c

branches:
 only:
 - master

osx_image: xcode7.1
xcode_sdk: iphonesimulator9.1 

script: xctool -project onthemap.xcodeproj -scheme onthemapTests build  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -enableCodeCoverage
after_success:
  - bash <(curl -s https://codecov.io/bash)